//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueensBeyondV._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalonAppointmentTable
    {
        public string Service_Id { get; set; }
        public string Full_Name { get; set; }
        public string Service_Request_Type { get; set; }
        public string Service_Details { get; set; }
        public System.DateTime Date_and_Time_Requested { get; set; }
    }
}
